/**
 * The Requesting concept exposes passthrough routes by default,
 * which allow POSTs to the route:
 *
 * /{REQUESTING_BASE_URL}/{Concept name}/{action or query}
 *
 * to passthrough directly to the concept action or query.
 * This is a convenient and natural way to expose concepts to
 * the world, but should only be done intentionally for public
 * actions and queries.
 *
 * This file allows you to explicitly set inclusions and exclusions
 * for passthrough routes:
 * - inclusions: those that you can justify their inclusion
 * - exclusions: those to exclude, using Requesting routes instead
 */

/**
 * INCLUSIONS
 *
 * Each inclusion must include a justification for why you think
 * the passthrough is appropriate (e.g. public query).
 *
 * inclusions = {"route": "justification"}
 */

export const inclusions: Record<string, string> = {
  // BodyMapGeneration - User actions (validate ownership via user parameter)
  "/api/BodyMapGeneration/saveMap": "user action that validates ownership - only saves the user's own current map",
  "/api/BodyMapGeneration/clearMap": "user action that validates ownership - only clears the user's own current map",
  // BodyMapGeneration - Query methods (validate ownership via user parameter)
  "/api/BodyMapGeneration/_getCurrentMap": "query that validates ownership - only returns the user's own current map",
  "/api/BodyMapGeneration/_getSavedMaps": "query that validates ownership - only returns the user's own saved maps",
  
  // MapSummaryGeneration - Query methods (validate ownership via user parameter in summary queries)
  "/api/MapSummaryGeneration/_getSummary": "query that validates ownership - only returns summaries owned by the user",
  "/api/MapSummaryGeneration/_getUserSummaries": "query that validates ownership - only returns summaries for the specified user",
  
  // PainLocationScoring - User actions (validate ownership via validateMapOwnership/validateRegionOwnership)
  "/api/PainLocationScoring/addRegion": "user action that validates map ownership - only adds regions to user's own maps",
  "/api/PainLocationScoring/scoreRegion": "user action that validates region ownership - only scores regions on user's own maps",
  "/api/PainLocationScoring/deleteRegion": "user action that validates region ownership - only deletes regions from user's own maps",
  // PainLocationScoring - Query methods (validate ownership via validateMapOwnership/validateRegionOwnership)
  "/api/PainLocationScoring/_getRegion": "query that validates region ownership - only returns regions owned by the user",
  "/api/PainLocationScoring/_getRegionsForMap": "query that validates map ownership - only returns regions for user's own maps",
  
  // UserAuthentication - Query methods (exposed for frontend to check user/session state)
  "/api/UserAuthentication/_getUser": "query that returns user state by username - used by frontend for auth state checks",
  "/api/UserAuthentication/_getSession": "query that returns session state by session ID - used by frontend for session validation",
};

/**
 * EXCLUSIONS
 *
 * Excluded routes fall back to the Requesting concept, and will
 * instead trigger the normal Requesting.request action. As this
 * is the intended behavior, no justification is necessary.
 *
 * exclusions = ["route"]
 */

export const exclusions: Array<string> = [
  // BodyMapGeneration - System/backend actions (handled by syncs)
  "/api/BodyMapGeneration/triggerDailyMapGeneration", // System action - should be run by cron/scheduled task, not by users
  "/api/BodyMapGeneration/generateMap", // Maps should be auto-generated by backend/syncs (e.g., on user registration), not manually by users
  
  // MapSummaryGeneration - Internal calculation methods (should be handled by backend/syncs)
  "/api/MapSummaryGeneration/sumRegion", // Internal calculation step, not a user-facing action - handled by backend/syncs
  "/api/MapSummaryGeneration/summarise", // Internal calculation step, not a user-facing action - handled by backend/syncs
  "/api/MapSummaryGeneration/generateAndStoreSummary", // Should be triggered by backend/sync, not directly by users
  "/api/MapSummaryGeneration/calculateMedian", // Private helper method, not exposed
  // MapSummaryGeneration - PDF exports (should go through Requesting concept with session validation via syncs)
  "/api/MapSummaryGeneration/exportSummaryAsPDF", // Should go through Requesting concept for proper auth/session validation
  "/api/MapSummaryGeneration/exportUserSummariesAsPDF", // Should go through Requesting concept for proper auth/session validation
  
  // PainLocationScoring - Private/internal methods (handled by syncs)
  "/api/PainLocationScoring/validateMapOwnership", // Private helper method, not exposed
  "/api/PainLocationScoring/validateRegionOwnership", // Private helper method, not exposed
  "/api/PainLocationScoring/_addMapForTesting", // Testing helper, should not be public
  "/api/PainLocationScoring/trackMap", // Internal sync method - called by syncs when maps are generated, not by users
  
  // UserAuthentication - All actions should go through Requesting/syncs for proper auth flow, logging, and session validation
  "/api/UserAuthentication/register", // Should go through Requesting concept for logging, auditing, and validation
  "/api/UserAuthentication/login", // Should go through Requesting concept for logging, auditing, and session management
  "/api/UserAuthentication/logout", // Should go through Requesting concept for logging and session management
  "/api/UserAuthentication/getUserMaps", // Should go through Requesting concept with session validation for proper auth flow
];
